[package]
name = "iri_pet_world"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
borsh = "0.10.3"
borsh-derive = "0.10.3"
solana-program = "1.18.26"
thiserror = "1.0.69"

[features]
no-entrypoint = []
